version: '3'

services:
  tourney-db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tourney
      MYSQL_ROOT_PASSWORD: tourney
      MYSQL_PASSWORD: tourney
      MYSQL_USER: tourney
