CREATE TABLE games (
    id INT(11) NOT NULL AUTO_INCREMENT,
    tournament_id INT(11) NOT NULL,
    team_1_id INT(11) NOT NULL,
    team_2_id INT(11) NOT NULL,
    team_batting INT(11),
    inning INT(11),
    score VARCHAR(250),
    batter INT(11),
    strikes INT(11),
    balls INT(11),
    catcher INT(11),
    pitcher INT(11),
    base_1 INT(11),
    base_2 INT(11),
    short_stop INT(11),
    base_3 INT(11),
    right_field INT(11),
    center_field INT(11),
    left_field INT(11),
    PRIMARY KEY (id)
);
