CREATE TABLE games (
    id INT(11) NOT NULL AUTO_INCREMENT,
    game_level INT(11) NOT NULL,
    tournament_id INT(11) NOT NULL,
    team_1_id INT(11) NOT NULL,
    team_2_id INT(11) NOT NULL,
    team_batting INT(11),
    inning INT(11),
    score VARCHAR(250),
    batter VARCHAR(250),
    strikes INT(11),
    balls INT(11),
    pitcher VARCHAR(250),
    catcher VARCHAR(250),
    base_1 VARCHAR(250),
    base_2 VARCHAR(250),
    short_stop VARCHAR(250),
    base_3 VARCHAR(250),
    right_field VARCHAR(250),
    center_field VARCHAR(250),
    left_field VARCHAR(250),
    PRIMARY KEY (id)
);
